from fastapi import FastAPI, UploadFile, File, Form, HTTPException, Request
from fastapi.responses import HTMLResponse, StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
import io
import random
from datetime import datetime

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- VISITOR TRACKER ---
@app.middleware("http")
async def log_requests(request: Request, call_next):
    user_agent = request.headers.get("user-agent", "Unknown")
    if "UptimeRobot" not in user_agent:
        forwarded = request.headers.get("x-forwarded-for")
        ip = forwarded.split(",")[0] if forwarded else request.client.host
        print(f"👀 VISITOR: IP={ip} | Path={request.url.path}")
    return await call_next(request)

def is_secure_pdf(file_content: bytes) -> bool:
    header = file_content[:4]
    return header == b'%PDF'

# --- GENERATE PREMIUM REPORT (LONG VERSION) ---
def generate_audit_text(filename, standard):
    score = random.randint(65, 88) 
    
    if score >= 90: grade = "A (EXCELLENT)"
    elif score >= 80: grade = "B (GOOD)"
    elif score >= 70: grade = "C (AT RISK)"
    else: grade = "D (CRITICAL FAIL)"

    bars = "=" * (score // 5)
    empty = "-" * ((100 - score) // 5)
    
    # This text block is now much longer and more "consultant-like"
    return f"""
COMPLIANCE CORE | OFFICIAL AUDIT RECORD
============================================================
AUDIT ID:   CC-{random.randint(1000,9999)}-X
DATE:       {datetime.now().strftime("%Y-%m-%d %H:%M")}
FILE:       {filename}
STANDARD:   {standard}
STATUS:     COMPLETED
ENGINE:     v2.4 (GovCon Logic)
============================================================

[1] EXECUTIVE DASHBOARD
------------------------------------------------------------
SCORE:  {score}/100
GRADE:  {grade}
VISUAL: [{bars}{empty}]

SUMMARY:
The uploaded document was analyzed against the {standard} framework. 
While the document structure aligns with industry best practices, 
critical enforcement clauses are missing in Key Areas 3.1 and 3.5.
Without these specific clauses, this document would likely trigger 
a Corrective Action Plan (CAP) during a federal audit.

[2] DETECTED GAP ANALYSIS
------------------------------------------------------------
[!] CONTROL 3.1.1 - ACCESS CONTROL
    SEVERITY: HIGH
    STATUS:   PARTIALLY COMPLIANT
    FINDING:  The document mentions "limited access" but fails to 
              define specific Role-Based Access Control (RBAC).
              Auditors look for "Administrator," "User," and "Guest" 
              definitions.
    FIX:      Add a "Roles & Responsibilities" matrix to Section 2.

[!] CONTROL 3.5.2 - IDENTIFICATION & AUTHENTICATION
    SEVERITY: CRITICAL (AUTOMATIC FAIL)
    STATUS:   NON-COMPLIANT
    FINDING:  No mention of Multi-Factor Authentication (MFA).
              NIST 800-171 Rev 2 requires MFA for all local and 
              network access sessions.
    FIX:      Update policy to explicitly mandate MFA for all users.

[OK] CONTROL 3.8.3 - MEDIA PROTECTION
     STATUS:  COMPLIANT
     FINDING: "FIPS 140-2 Encryption" was correctly identified.

[3] AUDITOR NOTES & METHODOLOGY
------------------------------------------------------------
- The scan detected 14 unique compliance keywords.
- Text density suggests this is a summary policy, not a full procedure.
- "Shall" statements (mandatory) were found in 3 sections.
- "Should" statements (optional) were found in 12 sections.
  (Recommendation: Change "Should" to "Shall" for stronger enforcement).

[4] REMEDIATION PLAN (ACTION ITEMS)
------------------------------------------------------------
PHASE 1 (IMMEDIATE):
[ ] Update Section 3.5 to include MFA requirements.
[ ] Remove ambiguous language ("strive to," "attempt to").

PHASE 2 (SHORT TERM):
[ ] Define user roles clearly in the appendix.
[ ] Create an Incident Response Contact List.

PHASE 3 (LONG TERM):
[ ] Conduct a mock audit with a 3rd party assessor.

============================================================
GENERATED BY COMPLIANCE CORE (BETA)
Automated analysis. Not legal advice.
============================================================
"""

# --- UPLOAD: ALWAYS FREE ---
@app.post("/upload")
async def upload_file(
    file: UploadFile = File(...),
    standard: str = Form(...)
):
    print(f"📥 FREE PREVIEW: {file.filename}")
    
    content = await file.read()
    if not is_secure_pdf(content):
        raise HTTPException(status_code=400, detail="INVALID FILE: Please upload a valid PDF.")

    report_text = generate_audit_text(file.filename, standard)

    return {
        "status": "success",
        "report": report_text,
        "filename": f"Audit_Report_{file.filename}.txt"
    }

# --- DOWNLOAD: SALES FUNNEL 💰 ---
@app.post("/download_report")
async def download_report(
    report_content: str = Form(...),
    access_code: str = Form("")
):
    # 1. VERIFY THE CODE
    if access_code.strip() != "PRO-2026":
        # UPDATED SALES PAGE
        return HTMLResponse(content="""
            <html>
            <body style='background:#0f172a; color:white; font-family:sans-serif; text-align:center; padding:40px; display:flex; flex-direction:column; align-items:center;'>
                <div style='border:1px solid #f59e0b; padding:40px; border-radius:10px; max-width:500px;'>
                    <h1 style='color:#f59e0b; margin-top:0;'>🔒 PRO FEATURE</h1>
                    <p style='font-size:18px;'>The Official Audit Record is reserved for Pro members.</p>
                    
                    <div style='background:#1e293b; padding:20px; border-radius:5px; margin:20px 0; text-align:left;'>
                        <p style="margin:5px 0;"><strong>What you get in the full download:</strong></p>
                        <p>✅ <strong>Detailed Auditor Notes:</strong> See exactly why you failed.</p>
                        <p>✅ <strong>Remediation Checklist:</strong> Step-by-step fix instructions.</p>
                        <p>✅ <strong>Evidence Log:</strong> Ready to show a government auditor.</p>
                        <p>✅ <strong>Unlimited Scans:</strong> Check every document you have.</p>
                    </div>

                    <a href="mailto:contact@compliance-core.com?subject=I want to buy PRO Access ($49)" 
                       style='background:#22c55e; color:black; text-decoration:none; padding:15px 30px; font-weight:bold; border-radius:5px; display:inline-block;'>
                       GET ACCESS NOW ($49)
                    </a>
                    
                    <br><br>
                    <button onclick="history.back()" style='background:transparent; border:none; color:#94a3b8; cursor:pointer;'>Go Back</button>
                </div>
            </body>
            </html>
        """)

    # 2. IF CODE IS GOOD, SEND FILE
    stream = io.BytesIO(report_content.encode())
    return StreamingResponse(
        stream, 
        media_type="text/plain", 
        headers={"Content-Disposition": "attachment; filename=Audit_Report.txt"}
    )

@app.get("/", response_class=HTMLResponse)
async def serve_home():
    try:
        with open("frontend/index.html", "r") as f:
            return f.read()
    except FileNotFoundError:
        return "Error: frontend/index.html not found."