from fastapi import FastAPI, UploadFile, File, Form, HTTPException, Request
from fastapi.responses import HTMLResponse, StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
import io
import random
from datetime import datetime

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- VISITOR TRACKER ---
@app.middleware("http")
async def log_requests(request: Request, call_next):
    user_agent = request.headers.get("user-agent", "Unknown")
    if "UptimeRobot" not in user_agent:
        forwarded = request.headers.get("x-forwarded-for")
        ip = forwarded.split(",")[0] if forwarded else request.client.host
        print(f"👀 VISITOR: IP={ip} | Path={request.url.path}")
    return await call_next(request)

def is_secure_pdf(file_content: bytes) -> bool:
    header = file_content[:4]
    return header == b'%PDF'

def generate_audit_text(filename, standard):
    score = random.randint(65, 88) 
    
    if score >= 90: grade = "A (EXCELLENT)"
    elif score >= 80: grade = "B (GOOD)"
    elif score >= 70: grade = "C (AT RISK)"
    else: grade = "D (CRITICAL FAIL)"

    bars = "=" * (score // 5)
    empty = "-" * ((100 - score) // 5)
    
    return f"""
COMPLIANCE CORE | OFFICIAL AUDIT RECORD
============================================================
AUDIT ID:   CC-{random.randint(1000,9999)}-X
DATE:       {datetime.now().strftime("%Y-%m-%d %H:%M")}
FILE:       {filename}
STANDARD:   {standard}
STATUS:     COMPLETED
============================================================

[1] OVERALL COMPLIANCE SCORE
------------------------------------------------------------
SCORE:  {score}/100
GRADE:  {grade}
VISUAL: [{bars}{empty}]

EXECUTIVE SUMMARY:
Analysis of {standard} controls indicates the document meets 
formatting baselines but lacks enforcement language.

[2] CRITICAL GAP ANALYSIS
------------------------------------------------------------
[!] CONTROL 3.1.1 - ACCESS CONTROL
    STATUS:  PARTIALLY COMPLIANT
    FIX:     Add a "Roles & Responsibilities" matrix.

[!] CONTROL 3.5.2 - AUTHENTICATION
    STATUS:  NON-COMPLIANT (CRITICAL)
    FIX:     Update policy to explicitly mandate MFA.

[OK] CONTROL 3.8.3 - MEDIA PROTECTION
     STATUS:  COMPLIANT
     FINDING: Encryption identified.

[3] REMEDIATION PLAN
------------------------------------------------------------
1. Update Section 3.5 to include MFA requirements.
2. Define user roles clearly in the appendix.

============================================================
GENERATED BY COMPLIANCE CORE (BETA)
Automated analysis. Not legal advice.
============================================================
"""

# --- UPLOAD: ALWAYS FREE ---
@app.post("/upload")
async def upload_file(
    file: UploadFile = File(...),
    standard: str = Form(...)
):
    print(f"📥 FREE PREVIEW: {file.filename}")
    
    content = await file.read()
    if not is_secure_pdf(content):
        raise HTTPException(status_code=400, detail="INVALID FILE: Please upload a valid PDF.")

    report_text = generate_audit_text(file.filename, standard)

    return {
        "status": "success",
        "report": report_text,
        "filename": f"Audit_Report_{file.filename}.txt"
    }

# --- DOWNLOAD: PAYWALL LOCKED 🔒 ---
@app.post("/download_report")
async def download_report(
    report_content: str = Form(...),
    access_code: str = Form("")
):
    # 1. VERIFY THE CODE
    if access_code.strip() != "PRO-2026":
        # If code is wrong, return an Error HTML page
        return HTMLResponse(content="""
            <html>
            <body style='background:#0f172a; color:#ef4444; font-family:sans-serif; text-align:center; padding-top:50px;'>
                <h1>❌ ACCESS DENIED</h1>
                <p>The code you entered is invalid.</p>
                <p style='color:white;'>Please purchase a PRO license to download files.</p>
                <button onclick="window.close()" style="padding:10px; cursor:pointer;">Close Tab</button>
            </body>
            </html>
        """, status_code=403)

    # 2. IF CODE IS GOOD, SEND FILE
    stream = io.BytesIO(report_content.encode())
    return StreamingResponse(
        stream, 
        media_type="text/plain", 
        headers={"Content-Disposition": "attachment; filename=Audit_Report.txt"}
    )

@app.get("/", response_class=HTMLResponse)
async def serve_home():
    try:
        with open("frontend/index.html", "r") as f:
            return f.read()
    except FileNotFoundError:
        return "Error: frontend/index.html not found."